#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources
usermodmap=${XDG_CONFIG_HOME:-$HOME/.config}/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

DEFAULT_SESSION=dwm
export XDG_CURRENT_DESKTOP=X-Generic
export QT_QPA_PLATFORM="xcb"

# merge in defaults and keymaps


[ -f $sysresources ] && xrdb -merge $sysresources

[ -f $sysmodmap ] && xrdb -merge $sysmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -f "$usermodmap" ] && xrdb -merge "$usermodmap"

# Start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
      for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	    [ -x "$f" ] && . "$f"
      done
      unset f
fi

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . "$HOME"/.xprofile

systemctl --user import-environment XDG_CURRENT_DESKTOP DISPLAY # Import which display X server is using for clipmenud and dunst
systemctl --no-block --user start xsession.target
exec $DEFAULT_SESSION
