#!/bin/sh
set -xe

MAIN_BRANCH="$(git branch --format='%(refname:short)' | tail -1)"
OTHER_BRANCHES="$(git branch --format='%(refname:short)' | head -n -1 | tr '\n' ' ')"

git stash
for branch in $OTHER_BRANCHES
do
	git switch "$branch"
	git rebase "$MAIN_BRANCH"
	git pull --rebase "$MAIN_BRANCH"
done
git switch "$MAIN_BRANCH"
git stash apply
git stash drop
