#!/bin/sh
set -e

ORIGINAL_BRANCH="$(git branch --show-current)"
CHERRY_PICK_BRANCH="$(git branch | sort --reverse | sed '/^\*/d;s/ //g;1q')"

commits=$(git log --pretty=format:%H origin/"$ORIGINAL_BRANCH"..HEAD | sort --reverse)

# Switch to the cherry-pick branch
printf '\033[36m%s\033[0m\n' "git switch $CHERRY_PICK_BRANCH"
git switch "$CHERRY_PICK_BRANCH"

for commit in $commits
do
	printf '\033[36m%s\033[0m\n' "git cherry-pick $commit"
	if ! git cherry-pick "$commit";
	then
		echo "Cherry-pick encountered conflicts. Please resolve them manually."
		exit 1
	fi
done

chmod --quiet u-x "$0"
printf '\033[36m%s\033[0m\n' "git push"
git push 2>/dev/null
chmod --quiet u+x "$0"

printf '\033[36m%s\033[0m\n' "git switch $ORIGINAL_BRANCH"
git switch "$ORIGINAL_BRANCH"
