" vim:fileencoding=utf-8:foldmethod=marker

" Add XDG Base directory to runtimepath
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')
set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')
if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
let mapleader = " " " Leader key

let g:enable_plugins = v:true

" Plugins {{{
if g:enable_plugins
	let data_dir = '~/.config/vim'

	if empty(glob(data_dir . '/autoload/plug.vim'))
		silent execute '!curl --fail --location --output '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
		autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
	endif

	autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
				\| PlugInstall --sync | source $MYVIMRC
				\| endif

	call plug#begin('$XDG_DATA_HOME/vim/plug')

	Plug 'airblade/vim-gitgutter'
	Plug 'dracula/vim', { 'as': 'Dracula' }
	Plug 'farmergreg/vim-lastplace'
	Plug 'ghifarit53/tokyonight-vim'
	Plug 'iamcco/markdown-preview.nvim'
	Plug 'joshdick/onedark.vim'
	Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
	Plug 'tpope/vim-commentary'
	Plug 'tpope/vim-fugitive'
	Plug 'tpope/vim-sensible'
	Plug 'tpope/vim-surround'

	call plug#end()
endif
" }}}


" Options {{{
colorscheme habamax
highlight ColorColumn ctermbg=lightgray guibg=red
set foldenable
set background=dark
set encoding=UTF-8
set hlsearch
set ignorecase smartcase
set incsearch
set linebreak
set number
set scrolloff=999
set termguicolors
set wildmenu
syntax enable
" }}}


" AutoCmd {{{
autocmd BufWritePost *.service !systemctl --user daemon-reload
autocmd BufWritePost sxhkdrc !systemctl restart --user sxhkd
autocmd BufWritePost swhkdrc !systemctl restart --user hotkeys
autocmd BufWritePost xmonad.hs !xmonad --recompile
autocmd BufWritePost .Xresources !xrdb ~/.Xresources
autocmd BufWritePost .bashrc !source .bashrc 	
" }}}


" Commands {{{
command! Reload execute "source $MYVIMRC"
" }}}


" Keybindings {{{
nnoremap <C-h> :nohlsearch<CR>
nnoremap <Down> :resize +2<CR>
nnoremap J mzJ`z
nnoremap <leader>tc :tabclose<CR>
nnoremap <Left> :vertical resize -2<CR>
nnoremap <Right> :vertical resize +2<CR>
nnoremap <Up> :resize -2<CR>
nnoremap Y yg$
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
" }}}
