local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pb', builtin.buffers, {})
vim.keymap.set('n', '<leader>pc', builtin.colorscheme, {})
vim.keymap.set('n', '<leader>pC', builtin.git_branches, {})
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>pg', builtin.git_files, {})
vim.keymap.set('n', '<leader>pG', builtin.live_grep, {})
vim.keymap.set('n', '<leader>ph', builtin.help_tags, {})
