#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "System Shutdown" --class shutdown {
	echo "System shutting down..."
	sleep 2
	halt
}

menuentry "System Restart" --class restart {
	echo "System rebooting..."
	sleep 2
	reboot
}

menuentry "UEFI Shell" {
	insmod fat
	insmod chain
	search --no-floppy --set=root --file /Shell_Full.efi
	chainloader /Shell_Full.efi
}

menuentry "gdisk" {
	insmod fat
	insmod chain
	search --no-floppy --set=root --file /EFI/tools/gdisk_x64.efi
	chainloader /EFI/tools/gdisk_x64.efi
}
