#!/usr/bin/env zsh

command -v fzf >/dev/null 2>&1 && command -v kubectl >/dev/null 2>&1 && {
	source <(kubectl completion zsh | sed 's#${requestComp} 2>/dev/null#${requestComp} 2>/dev/null | head -n -1 | fzf  --multi=0 #g')
}
