#!/usr/bin/env bash

_change-volume_complete() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	case ${prev} in
		change-volume) opts="notify toggle-mute 1 2 5 10" ;;
		[0-9]|[0-9][0-9]|100) opts="+ -" ;;
	esac
	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

_change-brightness_complete() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	case ${prev} in
		change-brightness) opts="notify 1 2 5 10" ;;
		[0-9]|[0-9][0-9]|100) opts="+ -" ;;
	esac
	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

_counter() {
	local cur prev opts
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	opts="-h --help -n --no-notification -r --reverse -t --time"

	time_values="20 30 40"

	case "$prev" in
		-h | --help | -n | --no-notification | -r | --reverse)
			# no additional completions needed for these flags
			;;
		-t | --time)
			COMPREPLY=( $(compgen -W "${time_values}" -- ${cur}) )
			;;
		*)
			COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
			;;
	esac

	return 0
}

_notify-music() {
	local cur prev opts
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	opts="-h --help -n --no-notification -q --quiet"

	case "$prev" in
		-h | --help | -n | --no-notification | -q | --quiet)
			# no additional completions needed for these flags
			;;
		*)
			COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
			;;
	esac

	return 0
}

_startX_complete() {
	local cur
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}

	COMPREPLY=( $( compgen -W 'dwm awesome i3 xmonad' -- $cur ) )

	return 0
}

_startWayland_complete() {
	local cur
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}

	COMPREPLY=( $( compgen -W 'hyprland sway' -- $cur ) )

	return 0
}

_scratchpad()
{
	local cur prev opts
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	opts="-h --help -d --debug -c --class -n --name -t --title -L --lines -C --columns
	-e --command -T --terminal -w --working-directory"

	class_values="Scratchpad"
	name_values="Scratchpad"
	title_values="Scratchpad"
	lines_values="20 30 40"
	columns_values="90 100 110"

	case "$prev" in
		-h | --help | -d | --debug | -T | --terminal | -e | --command)
			# no additional completions needed for these flags
			;;
		-c | --class)
			COMPREPLY=( $(compgen -W "${class_values}" -- ${cur}) )
			;;
		-n | --name)
			COMPREPLY=( $(compgen -W "${name_values}" -- ${cur}) )
			;;
		-t | --title)
			COMPREPLY=( $(compgen -W "${title_values}" -- ${cur}) )
			;;
		-L | --lines)
			# complete integer values
			COMPREPLY=( $(compgen -W "${lines_values}" -- "$cur") )
			;;
		-C | --columns)
			# complete integer values
			COMPREPLY=( $(compgen -W "${columns_values}" -- "$cur") )
			;;
		-w | --working-directory)
			# complete directory names
			COMPREPLY=( $(compgen -d -- "$cur") )
			;;
		*)
			COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
			;;
	esac

	return 0
}

_wallpaper() {
	local cur prev opts
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	opts="-h --help next reset-timer"

	time_values="20 30 40"

	case "$prev" in
		-h | --help | next | reset-timer)
			# no additional completions needed for these flags
			;;
		*)
			COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
			;;
	esac

	return 0
}

_wallpaperLoop()
{
	local cur prev opts
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	opts="-h --help --enable-videos --disable-videos --mpv-options --sleep-interval"

	sleep_interval="60 600"

	case "$prev" in
		-h | --help | --enable-videos | --disable-videos | --mpv-options)
			# no additional completions needed for these flags
			;;
		--sleep-interval)
			COMPREPLY=( $(compgen -W "${sleep_interval}" -- ${cur}) )
			;;
		*)
			COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
			;;
	esac

	return 0
}

complete -F _change-volume_complete change-volume
complete -F _counter counter
complete -F _notify-music notify-music
complete -F _scratchpad scratchpad
complete -F _startWayland_complete startWayland
complete -F _startX_complete startX
complete -F _wallpaperLoop wallpaperLoop
complete -F _wallpaper wallpaper
